{
 "title": "Open Weather Map",
 "description": "Access current weather data for any location on Earth including over 200,000 cities!",
 "tags": [ "weather" ],
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Temperature",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "openweather_temperature", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Wind speed",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "velocitymph" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "openweather_windspeed", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Cloudiness",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "openweather_cloudiness", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Humidity",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "openweather_humidity", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Wind direction",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "openweather_winddegree", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Atmospheric pressure",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "openweather_pressure", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "targets": [
    { "expr": "openweather_temperature", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "openweather_humidity", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Atmospheric pressure",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "targets": [
    { "expr": "openweather_pressure", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Wind speed",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "velocitymph" } },
   "targets": [
    { "expr": "openweather_windspeed", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Cloudiness",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "openweather_cloudiness", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Rain in last hour",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "inches" } },
   "targets": [
    { "expr": "openweather_rain1h", "legendFormat": "__auto" }
   ]
  }
 ]
}